// Loading
export const LOADING_AUTH_STARTED = 'LOADING_AUTH_STARTED';
export const LOADING_AUTH_FINISHED = 'LOADING_AUTH_FINISHED';
export const LOADING_TICKET_STARTED = 'LOADING_TICKET_STARTED';
export const LOADING_TICKET_FINISHED = 'LOADING_TICKET_FINISHED';
export const LOADING_PROFILE_STARTED = 'LOADING_PROFILE_STARTED';
export const LOADING_PROFILE_FINISHED = 'LOADING_PROFILE_FINISHED';

// Auth
export const USER_LOGIN = "USER_LOGIN";

// Ticket
export const GET_ALL_TICKETS = 'GET_ALL_TICKETS';
export const UPLOAD_TICKET = 'UPLOAD_TICKET';
export const UPLOAD_IMAGE = 'UPLOAD_IMAGE';
export const LEGS_ARR = 'LEGS_ARR';
export const SAVE_FILE = 'SAVE_FILE';

// Profile
export const GET_PROFILE = "GET_PROFILE";

export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';